import classes from './Counter.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { counterActions } from '../store/index';

const Counter = () => {
  const dispatch = useDispatch();
  const counter = useSelector((state) => state.counter);
  const showCounter = useSelector((state) => state.showCounter);
  const incrementCounterHandler = (payload) => {
    dispatch(counterActions.increment(payload)); // eg. {type: 'INCREMENT', payload: 1} | payload is autogenerated key name
  };
  const decrementCounterHandler = (payload) => {
    dispatch(counterActions.decrement(payload));
  };

  const toggleCounterHandler = () => {
    dispatch(counterActions.toggleCounter());
  };
  return (
    <main className={classes.counter}>
      <h1>Redux Counter</h1>
      {showCounter && (
        <>
          <div className={classes.value}>{counter}</div>
          <button onClick={() => incrementCounterHandler(1)}>
            Increment Counter
          </button>
          <button onClick={() => decrementCounterHandler(1)}>
            Decrement Counter
          </button>
          <button onClick={() => incrementCounterHandler(5)}>
            Increment Counter by 5
          </button>
          <button onClick={() => decrementCounterHandler(10)}>
            Decrement Counter by 10
          </button>
        </>
      )}
      <button onClick={toggleCounterHandler}>Toggle Counter</button>
    </main>
  );
};

export default Counter;
